language: node_js
node_js:
- '8'
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  on:
    branch:
    - development
    - master
notifications:
  slack:
    secure: jQuEgNJNgzPv/nwYvoJrBFJV6ZaDCK+G75TcQjXdieEH47oIsWwGgaCD+jMIfujZDz3ak147ajQU4syhVSM2d/dgfU9+1A55tTIi5X4lh9/3u7LMAn48GkxKWZE3IqLJZ8f5oLFqMfU0pPSGa612mAH2Cs/k/87IyHilzkCb6Ilzl4Hq4efSKB1reBz30CrTL8e9QIBugib6Nqt+QLf0iNpciGxCfpIbP9Mm2HzV+l9LoCGseAtdSmYswDc4HWzdajEF3rCBylb0iMvqu50qrYrYWjZU3zDbmXZjRmjPKQ55/stvU4m6PhWPz8isa6EzU9GSwzBDPW63y12eVHkMkzsjENu1X/U8Ror4jPa3iOgmFiu6yYzOaHM0/ms5bCvV5QHPFNOw1HeTIn8kiwF0v1WVp3/bSbxhf1fuhUcU+9yqpg4FDVC4TyPHNQQ2XTS5yVF7tfc18HQKQxAwh2ok0DB+cy0AZw5DTUX+XWTxoM1/dVO+CfLS6qFwIpIHJgyNz9SVMPR3RjB5odvXSUI08Ggai6VPAvhYlMxLTR6Z7s3qjoRNM/tLI/kcGWZMmsUWmB/GzJHdMggv5Qp6hRE2HpfeDBnq/13OBVqVRz1wBTm1nH48P8UVFOzWys29wRPyrYaQ7gKvzsUuU6+W8hW58VZKYjuW5lZMGGqIh6Dfjbs=
