// @flow

export const authConstants = {
  REGISTER: 'AUTH_REGISTER',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_ERROR: 'AUTH_REGISTER_ERROR',

  LOGIN: 'AUTH_LOGIN',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_ERROR: 'AUTH_LOGIN_ERROR',

  LOGOUT: 'AUTH_LOGOUT',

  TOKEN_KEY: 'AUTH_TOKEN',
};
