// @flow

export const NOTE = {
  LIST: 'NOTE_LIST',
  LIST_ERROR: 'NOTE_LIST_ERROR',
  LIST_SUCCES: 'NOTE_LIST_SUCCES',
  SHARED_LIST: 'NOTE_SHARED_LIST',
  SHARED_LIST_ERROR: 'NOTE_SHARED_LIST_ERROR',
  SHARED_LIST_SUCCES: 'NOTE_SHARED_LIST_SUCCES',
  BY_ID: 'NOTE_BY_ID',
  BY_ID_SUCCESS: 'NOTE_BY_ID_SUCCESS',
  BY_ID_ERROR: 'NOTE_BY_ID_ERROR',
  SHARE: 'NOTE_SHARE',
  SHARE_ERROR: 'NOTE_SHARE_ERROR',
  SHARE_SUCCES: 'NOTE_SHARE_SUCCES',
  SAVE: 'NOTE_SAVE',
  SAVE_ERROR: 'NOTE_SAVE_ERROR',
  SAVE_SUCCES: 'NOTE_SAVE_SUCCES',
  EDIT: 'NOTE_EDIT',
  EDIT_ERROR: 'NOTE_EDIT_ERROR',
  EDIT_SUCCES: 'NOTE_EDIT_SUCCES',
};
